= Igualdad
<>Desigualdad
< Menor que…
>Mayor que…
<= Menor o igual que …
>= Mayor o igual que …

SELECT * FROM Series WHERE año_lanzamiento > 2015;
SELECT * FROM Series WHERE año_lanzamiento < 2015;
SELECT titulo, año_lanzamiento FROM Series WHERE año_lanzamiento > 2020;
