CREATE DATABASE IF NOT EXISTS EmpresaDB;

CREATE TABLE IF NOT EXISTS Departamentos (
depto_id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
ubicacion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Empleados (
empleado_id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
apellido VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
depto_id INT,
FOREIGN KEY(depto_id) REFERENCES Departamentos(depto_id)
ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Departamentos (
depto_id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
ubicacion VARCHAR(255)
);


CREATE INDEX idx_apellido ON Empleados(apellido);
